require("plugins.plugins-lazy")
require("core.options")
require("core.keymaps")

-- 插件
require("plugins/lualine")
require("plugins/nvim-tree")
-- require("plugins/navigator")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins/dashboard")
require("plugins/project")
require("plugins/markdown-preview")
require("plugins/null-ls")
require("plugins/nvim-dap")
require("plugins/nvim-dap-ui")
require("plugins/nvim-dap-go")
